// user authentication types
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'


// admin authentication types
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'
export const ADMIN_REGISTER_REQUEST = 'ADMIN_REGISTER_REQUEST'
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS'
export const ADMIN_REGISTER_FAILED = 'ADMIN_REGISTER_FAILED'

// user profile types
export const USER_CREATE_PROFILE_REQUEST = 'USER_CREATE_PROFILE_REQUEST'
export const USER_CREATE_PROFILE_SUCCESS = 'USER_CREATE_PROFILE_SUCCESS'
export const USER_CREATE_PROFILE_FAILED = 'USER_CREATE_PROFILE_FAILED'
export const USER_GET_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST'
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
export const USER_GET_PROFILE_FAILED = 'USER_GET_PROFILE_FAILED'

// user academics types
export const USER_CREATE_ACADEMICS_REQUEST = 'USER_CREATE_ACADEMICS_REQUEST'
export const USER_CREATE_ACADEMICS_SUCCESS = 'USER_CREATE_ACADEMICS_SUCCESS'
export const USER_CREATE_ACADEMICS_FAILED = 'USER_CREATE_ACADEMICS_FAILED'
export const USER_GET_ACADEMICS_REQUEST = 'USER_GET_ACADEMICS_REQUEST'
export const USER_GET_ACADEMICS_SUCCESS = 'USER_GET_ACADEMICS_SUCCESS'
export const USER_GET_ACADEMICS_FAILED = 'USER_GET_ACADEMICS_FAILED'

// admin academics
export const ADMIN_GET_ACADEMICS_REQUEST = 'ADMIN_GET_ACADEMICS_REQUEST'
export const ADMIN_GET_ACADEMICS_SUCCESS = 'ADMIN_GET_ACADEMICS_SUCCESS'
export const ADMIN_GET_ACADEMICS_FAILED = 'ADMIN_GET_ACADEMICS_FAILED'

// admin profile
export const ADMIN_GET_PROFILE_REQUEST = 'ADMIN_GET_PROFILE_REQUEST'
export const ADMIN_GET_PROFILE_SUCCESS = 'ADMIN_GET_PROFILE_SUCCESS'
export const ADMIN_GET_PROFILE_FAILED = 'ADMIN_GET_PROFILE_FAILED'